version: "3.9"

services:
  DB:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  Redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6380"

